
import __ASTRO_IMAGE_IMPORT_ZdahAS from "../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fback-office.md";
import __ASTRO_IMAGE_IMPORT_Z1GoL1Y from "../../assets/placeholders/hero-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomatizacion-de-procesos.md";
import __ASTRO_IMAGE_IMPORT_ZJf7iy from "../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomatizacion-industrial.md";
import __ASTRO_IMAGE_IMPORT_2dDSlW from "../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Ffront-office.md";
import __ASTRO_IMAGE_IMPORT_Z2tVyah from "../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fintegracion-electrica-y-control.md";
import __ASTRO_IMAGE_IMPORT_JGtN5 from "../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fmantenimiento-tecnico-industrial.md";
import __ASTRO_IMAGE_IMPORT_Z2lmdo8 from "../../assets/placeholders/hero-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Frobotica-inteligente.md";
import __ASTRO_IMAGE_IMPORT_Dw8KD from "../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fsoporte-tecnico.md";
import __ASTRO_IMAGE_IMPORT_Z1R2vbq from "../../assets/placeholders/cover-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcelda-robotizada-paletizado.md";
import __ASTRO_IMAGE_IMPORT_2iJ7Fz from "../../assets/placeholders/cover-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fintegracion-plc-hmi-linea.md";
import __ASTRO_IMAGE_IMPORT_sNrMG from "../../assets/placeholders/cover-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsoporte-continuidad-operacional.md";
export default new Map([["../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fback-office.md", __ASTRO_IMAGE_IMPORT_ZdahAS], ["../../assets/placeholders/hero-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomatizacion-de-procesos.md", __ASTRO_IMAGE_IMPORT_Z1GoL1Y], ["../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomatizacion-industrial.md", __ASTRO_IMAGE_IMPORT_ZJf7iy], ["../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Ffront-office.md", __ASTRO_IMAGE_IMPORT_2dDSlW], ["../../assets/placeholders/hero-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fintegracion-electrica-y-control.md", __ASTRO_IMAGE_IMPORT_Z2tVyah], ["../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fmantenimiento-tecnico-industrial.md", __ASTRO_IMAGE_IMPORT_JGtN5], ["../../assets/placeholders/hero-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Frobotica-inteligente.md", __ASTRO_IMAGE_IMPORT_Z2lmdo8], ["../../assets/placeholders/hero-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fsoporte-tecnico.md", __ASTRO_IMAGE_IMPORT_Dw8KD], ["../../assets/placeholders/cover-1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcelda-robotizada-paletizado.md", __ASTRO_IMAGE_IMPORT_Z1R2vbq], ["../../assets/placeholders/cover-2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fintegracion-plc-hmi-linea.md", __ASTRO_IMAGE_IMPORT_2iJ7Fz], ["../../assets/placeholders/cover-3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsoporte-continuidad-operacional.md", __ASTRO_IMAGE_IMPORT_sNrMG]]);
		